### ISSUE TITLE
propagate untranslated Rmd to workspace

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/AnVILPublish#4]
if i understand correctly the ipynb are propagated but not the Rmd.  if user is using an Rstudio-only runtime,
it is better to have the Rmd in a prominent place, preferably visible in the Files pane of Rstudio.

**Comment by mtmorgan** [comment]
Propagating the Rmd is somewhat redundant with their presence in the **built** package
```
> dir(system.file(package="AnVIL", "doc"), pattern="Rmd")
[1] "BiocDockstore.Rmd" "Introduction.Rmd"
```
One can navigate to these easily in RStudio (e.g., through package help) but only if one knows where to look.

So the question is how to make these existing documents more prominent in RStudio

**Comment by vjcitn** [comment]
Sounds like a copy from the doc folder to the /home/rstudio on anvil may do the trick.  I'll look into it,
and make another argument/PR.

**Comment by mtmorgan** [comment]
Unfortunately that location is a runtime location, not a workspace location, so user-specfic. I though maybe the documents could be copied onto the google bucket but we've seen that buckets are not cloned when workspaces are cloned. There must be some magic for the /notebooks? location on the bucket, because this is where the ipynb notebooks are located, and these are copied to a cloned workspace. The files could be placed, maybe, as blobs in the Workspace DATA tab under TABLES  or REFERENCE DATA or Workspace Data (so they'd be associated with the workspace; these elements could be created with, e.g., `AnVIL::avtable_import()`) but this would not make them obvious to an RStudio user...

**Comment by vjcitn** [comment]
Can this be raised in the standup?  Getting them into the data space is a first step, but what could be done to
move them closer?  It must be possible but needs a UI element on the same order as NOTEBOOKS tab.

**Comment by vjcitn** [comment]
Here's a package that seems to cause problems for the current publish approach:  https://github.com/vjcitn/Rcollectl ... the vignette was started with biocthis.  I will try to get more details on issues but somehow it completes and there is nothing in workflow Description -- https://app.terra.bio/#workspaces/landmarkanvil2/Bioconductor-Package-Rcollectl is now readable by bioconductor_user@firecloud.org

**Comment by mtmorgan** [comment]
The title of this issue (propagating Rmd to the workspace) is accomplished with https://github.com/Bioconductor/AnVILPublish/pull/6 so I'll close the issue. If the other topics are still open and need pursuing please open new issues.
